# -*- coding: utf-8 -*-
"""IA Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kdf51xAJ4FmZC5UbnLXD8fq1IxZHQpzI
"""

caminhos = {
  'A' : ['B','D','G'],
  'D' : ['A','G','H'],
  'G' : ['A','D','T'],
  'D' : ['A','G','H'],
  'B' : ['A'],
  'T' : ['G'],
  'H' : ['D','P'],
  'P' : ['H']
}

visitado = []
def bfs(visitado,caminhos, comeco, saida):
  fila = []  
  fila.append(comeco)
  stringCaminho = "" 
  while fila:    
    s = fila.pop(0)
    no = s[-1]    
    if no not in visitado:      
      vizinhos = caminhos[no]        
      for neighbour in vizinhos:
        caminho = list(s)
        caminho.append(neighbour)
        fila.append(caminho)
        if neighbour == saida:
          for x in caminho:
            stringCaminho = stringCaminho + x 
            if x != caminho[len(caminho)-1]:
              stringCaminho = stringCaminho + " -> "                  
          return stringCaminho
      visitado.append(no)     
      

bfs(visitado,caminhos,'A','T')